name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou a branch de sua preferência
  pull_request:
    branches:
      - main  # ou a branch de sua preferência

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # ou qualquer versão necessária para o seu projeto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # instale as dependências do seu projeto
          pip install pytest-playwright  # se o pytest-playwright for necessário
          python -m playwright install  # instalar os navegadores do Playwright

  test:
    runs-on: ubuntu-latest
    needs: install_dependencies  # este job depende do 'install_dependencies' para ser executado

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-playwright
          python -m playwright install

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q  # ajuste os parâmetros de pytest conforme necessário
