name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

  test:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          - name: Start application
          run: |
            nohup python app.py > application.log 2>&1 &
          
      - name: Wait for application to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8000 > /dev/null; then
              echo "Application is ready!"
              break
            fi
            echo "Waiting for application..."
            sleep 2
          done
        
      - name: Check application logs
        if: failure()
        run: |
          echo "Application failed to start, logs:"
          cat application.log   

      - name: Run tests with pytest
        run: |
          pytest --tracing=retain-on-failure
